export const P0_TOOL_NAMES = [
  "project_status",
  "inspect_project",
  "get_timeline",
  "read_transcript",
  "get_comments",
  "select_branch",
  "control_playback",
  "add_comment",
  "propose_comment_resolution",
  "create_cut_branch",
  "apply_edit_batch",
  "style_captions",
  "place_broll",
  "place_clip",
  "place_audio",
  "set_transition",
  "add_transition",
  "split_clip",
  "trim_clip",
  "set_gain",
  "mute_track",
  "delete_clip",
  "import_media",
  "set_crop",
  "preview_range",
  "compare_cuts",
  "undo_edit",
  "redo_edit",
] as const;

export const HUMAN_ONLY_ABSENT = [
  "lock_range",
  "unlock_range",
  "accept_branch",
  "export",
  "publish",
  "delete_project",
];
